model:

  architecture: transformer   # choose: lstm | transformer | vae

  common:
    vocab_size: null
    block_size: 128


  lstm:
    embedding_dim: 128
    hidden_dim: 128
    num_layers: 2
    dropout: 0.2
    

  transformer:
    embedding_dim: 64
    n_head: 8
    n_layer: 6
    dropout: 0.1


training:

  batch_size: 128
  learning_rate: 0.001
  epochs: 40
  train_size: 0.8
  dataset_size: 'none'

rl:
  steps : 200


sampling:
  block_size: 128
  temperature: 1.2
